# -*- coding: utf-8 -*-
"""data_preprocessing_and_insert_sql.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OytBbV0eGzIxUE-fHvyoACJLu1MI_cWJ

구글 드라이브 연결
"""

from google.colab import drive
drive.mount('/content/drive')

"""재해 데이터셋에서 사용할 컬럼만 추출"""

# 라이브러리
import pandas as pd

# Google Drive 파일 경로 지정
file_path = "/content/drive/MyDrive/4-2 빅데이터응용/original dataset/public_emdat_custom_request_2025-11-02_209c5476-8f25-40a3-80fe-18b6e00f62bc.xlsx"

# 엑셀 불러오기
df = pd.read_excel(file_path)

# 필요한 열만 선택
columns_to_keep = [
    "ISO",
    "DisNo.",
    "Country",
    "Disaster Group",
    "Disaster Subgroup",
    "Disaster Type",
    "Disaster Subtype",
    "Start Year",
    "End Year",
    "Total Deaths",
    "Total Affected",
    "Total Damage ('000 US$)"
]
df_clean = df[columns_to_keep]

# MySQL 컬럼명으로 통일
df_clean.columns = [
    "iso_code",
    "disno",
    "country",
    "disaster_group",
    "disaster_subgroup",
    "disaster_type",
    "disaster_subtype",
    "start_year",
    "end_year",
    "total_deaths",
    "total_affected",
    "total_damage_thousand_usd"
]

# 결측치 → NULL
df_clean = df_clean.fillna("NULL")

# 정제된 CSV 저장 (내 드라이브에 저장)
output_path = "/content/drive/MyDrive/4-2 빅데이터응용/disaster_clean.csv"
df_clean.to_csv(output_path, index=False)

print("정제 완료! 파일이 이 경로에 저장됨:\n", output_path)

# 미리보기
df_clean.head(10)

"""월평균 기온 데이터셋에서 사용할 컬럼만 추출"""

import pandas as pd

# Google Drive 파일 경로 지정
file_path = "/content/drive/MyDrive/4-2 빅데이터응용/original dataset/average-monthly-surface-temperature.csv"

# CSV 불러오기
df = pd.read_csv(file_path)

# 'Day' 제거, 연평균 컬럼만 유지
columns_to_keep = ["Entity", "Code", "year", "Average surface temperature.1"]
df_clean = df[columns_to_keep]

# 컬럼명 통일
df_clean.columns = [
    "country",
    "iso_code",
    "measurement_year",
    "avg_temperature_celsius"
]

# 국가+연도 기준으로 중복 제거 (연평균 1개만 남기기)
df_clean = (
    df_clean.sort_values(["iso_code", "measurement_year"])     # 순서 정리
            .drop_duplicates(subset=["iso_code", "measurement_year"], keep="first")
)

# 결측치 처리 (NaN → NULL)
df_clean = df_clean.fillna("NULL")

# 내 드라이브에 저장
output_path = "/content/drive/MyDrive/4-2 빅데이터응용/temperature_clean.csv"
df_clean.to_csv(output_path, index=False)

print("연평균 데이터 정제 완료! 저장 경로:\n", output_path)

# 일부 데이터 미리보기
df_clean.head(10)

"""

*  재해데이터셋과 월평균 기온 데이터셋의 국가명 통일

*  국가명 csv 생성

"""

import pandas as pd

# 파일 경로
disaster_path = "/content/drive/MyDrive/4-2 빅데이터응용/disaster_clean.csv"
temperature_path = "/content/drive/MyDrive/4-2 빅데이터응용/temperature_clean.csv"

# CSV 불러오기
df_disaster = pd.read_csv(disaster_path)
df_temp = pd.read_csv(temperature_path)

# NIAID와 'World' 제거 (온도 데이터)
df_temp = df_temp[~df_temp["country"].str.contains("NIAID", na=False)]
df_temp = df_temp[~df_temp["country"].str.strip().str.lower().isin(["world"])]

# 이름 통합 매핑
merge_map = {
    "Cote d'Ivoire": "Côte d'Ivoire",
    "Democratic Republic of Congo": "Democratic Republic of the Congo",
    "Netherlands (Kingdom of the)": "Netherlands",
    "Bolivia (Plurinational State of)": "Bolivia",
    "Cabo Verde": "Cape Verde",
    "China, Hong Kong Special Administrative Region": "Hong Kong",
    "China, Macao Special Administrative Region": "Macao",
    "Democratic People's Republic of Korea": "North Korea",
    "Iran (Islamic Republic of)": "Iran",
    "Lao People's Democratic Republic": "Laos",
    "Republic of Korea": "South Korea",
    "Republic of Moldova": "Moldova",
    "Russian Federation": "Russia",
    "State of Palestine": "Palestine",
    "Syrian Arab Republic": "Syria",
    "Taiwan (Province of China)": "Taiwan",
    "Timor-Leste": "East Timor",
    "Türkiye": "Turkey",
    "United Kingdom of Great Britain and Northern Ireland": "United Kingdom",
    "United Republic of Tanzania": "Tanzania",
    "United States of America": "United States",
    "Venezuela (Bolivarian Republic of)": "Venezuela",
    "Viet Nam": "Vietnam"
}

# 국가명 통합 적용
df_disaster["country"] = df_disaster["country"].replace(merge_map)
df_temp["country"] = df_temp["country"].replace(merge_map)
df_disaster["country"] = df_disaster["country"].replace("Côte d’Ivoire", "Côte d'Ivoire")

# 고유 국가명 추출
disaster_countries = set(df_disaster["country"].dropna().unique())
temperature_countries = set(df_temp["country"].dropna().unique())

# 분류
common_countries = sorted(list(disaster_countries & temperature_countries))
only_disaster = sorted([c for c in disaster_countries if c not in common_countries])
only_temperature = sorted([c for c in temperature_countries if c not in common_countries])

# 최종 통합 목록
final_countries = sorted(list(disaster_countries | temperature_countries))

# ISO 코드 매핑 통합 (둘 다 iso_code 컬럼 존재)
disaster_iso = df_disaster[["country", "iso_code"]].drop_duplicates()
temp_iso = df_temp[["country", "iso_code"]].drop_duplicates()

# 중복 제거하면서 병합 (우선순위: 재해 → 온도)
iso_map = pd.concat([disaster_iso, temp_iso]).drop_duplicates(subset=["country"], keep="first")

# 최종 국가 파일 생성
df_country = pd.DataFrame({"country_name": final_countries})
df_country = df_country.merge(iso_map, how="left", left_on="country_name", right_on="country").drop(columns=["country"])

# 파일 저장
df_disaster.to_csv("/content/drive/MyDrive/4-2 빅데이터응용/disaster_standardized_final.csv", index=False, encoding="utf-8-sig")
df_temp.to_csv("/content/drive/MyDrive/4-2 빅데이터응용/temperature_standardized_final.csv", index=False, encoding="utf-8-sig")
df_country.to_csv("/content/drive/MyDrive/4-2 빅데이터응용/country_unified_final.csv", index=False, encoding="utf-8-sig")

# 결과 요약
print(f"공통 국가 수: {len(common_countries)}개")
print(f"재해 전용: {len(only_disaster)}개")
print(f"온도 전용: {len(only_temperature)}개")
print(f"최종 통합 국가 수: {len(final_countries)}개\n")

print(f"저장 완료: country_unified_final.csv (ISO 코드 포함)")
print(f"ISO 코드 누락된 국가 수: {df_country['iso_code'].isna().sum()}개")

pip install pycountry-convert

"""국가명 csv에 대응하는 대륙 컬럼도 추가"""

import pandas as pd
import pycountry_convert as pc

# 불러오기
countries = pd.read_csv("/content/drive/MyDrive/4-2 빅데이터응용/country_unified_final.csv")

# 대륙 분류 함수
def get_continent(country_name):
    try:
        code = pc.country_name_to_country_alpha2(country_name)
        continent_code = pc.country_alpha2_to_continent_code(code)
        return {
            "AF": "Africa",
            "AS": "Asia",
            "EU": "Europe",
            "NA": "North America",
            "SA": "South America",
            "OC": "Oceania",
            "AN": "Antarctica"
        }.get(continent_code, None)
    except:
        return None

countries["continent_name"] = countries["country_name"].apply(get_continent)

# CSV로 저장
countries.to_csv("/content/drive/MyDrive/4-2 빅데이터응용/country_with_continent.csv", index=False, encoding="utf-8-sig")

# 대륙 테이블 (unique)
continents = countries["continent_name"].dropna().unique()
print(continents)

"""pycountry_convert 로 매칭 안되는 국가명은 수동으로 대륙 매칭


"""

import pandas as pd

df = pd.read_csv("/content/drive/MyDrive/4-2 빅데이터응용/country_with_continent.csv")

manual_continent_fix = {
    "Azores Islands": "Europe",
    "Canary Islands": "Africa",
    "East Timor": "Asia",
    "Kosovo": "Europe",
    "Micronesia (Federated States of)": "Oceania",
    "Saint Helena": "Africa",
    "Saint Martin (French Part)": "North America",
    "Serbia Montenegro": "Europe",
    "Sint Maarten (Dutch part)": "North America",
    "Wallis and Futuna Islands": "Oceania"
}

df["continent_name"] = df.apply(
    lambda row: manual_continent_fix.get(row["country_name"], row["continent_name"]),
    axis=1
)

# 수정된 파일 저장
df.to_csv("/content/drive/MyDrive/4-2 빅데이터응용/country_with_continent_fixed.csv", index=False, encoding="utf-8-sig")

"""* 국가, 대륙 csv
* disaster csv
* monthly temperature csv
* 세 파일을 이용해 insert 문 생성 후 sql 파일 생성

"""

import pandas as pd

# ================================
# 파일 경로
# ================================
country_path = "/content/drive/MyDrive/4-2 빅데이터응용/country_with_continent_fixed.csv"
disaster_path = "/content/drive/MyDrive/4-2 빅데이터응용/disaster_standardized_final.csv"
temp_path = "/content/drive/MyDrive/4-2 빅데이터응용/temperature_standardized_final.csv"

# CSV 불러오기
df_country = pd.read_csv(country_path)
df_disaster = pd.read_csv(disaster_path)
df_temp = pd.read_csv(temp_path)

# ================================
# 1️. continent
# ================================
continents = sorted(df_country["continent_name"].dropna().unique().tolist())
continent_sql = "INSERT INTO continent (continent_name) VALUES\n"
continent_sql += ",\n".join([f"('{c}')" for c in continents]) + ";\n\n"
continent_map = {name: idx + 1 for idx, name in enumerate(continents)}

# ================================
# 2️. country
# ================================
country_values = []
for i, row in df_country.iterrows():
    name = row.country_name.replace("'", "''")
    iso = row.iso_code
    cid = continent_map.get(row.continent_name, "NULL")
    country_values.append(f"('{name}', '{iso}', {cid})")

country_sql = (
    "INSERT INTO country (country_name, iso_code, continent_id) VALUES\n"
    + ",\n".join(country_values)
    + ";\n\n"
)
# ISO → country_id (1부터 순서대로)
country_id_map = {row.iso_code: i + 1 for i, row in df_country.iterrows()}

# ================================
# 3️. disaster_types
# ================================
disaster_types_df = df_disaster[
    ["disaster_group", "disaster_subgroup", "disaster_type", "disaster_subtype"]
].drop_duplicates(ignore_index=True)

disaster_type_values = []
for _, r in disaster_types_df.iterrows():
    # NULL 허용 (NaN 방지)
    g = r.disaster_group if pd.notna(r.disaster_group) else "NULL"
    sg = r.disaster_subgroup if pd.notna(r.disaster_subgroup) else "NULL"
    t = r.disaster_type if pd.notna(r.disaster_type) else "NULL"
    st = r.disaster_subtype if pd.notna(r.disaster_subtype) else "NULL"
    disaster_type_values.append(f"('{g}', '{sg}', '{t}', '{st}')")

disaster_type_sql = (
    "INSERT INTO disaster_types (disaster_group, disaster_subgroup, disaster_type, disaster_subtype) VALUES\n"
    + ",\n".join(disaster_type_values)
    + ";\n\n"
)

# FK 매핑
disaster_type_map = {
    (r.disaster_group, r.disaster_subgroup, r.disaster_type, r.disaster_subtype): i + 1
    for i, r in disaster_types_df.iterrows()
}

# ================================
# 4️. disasters
# ================================
disaster_values = []
for _, r in df_disaster.iterrows():
    cid = country_id_map.get(r.iso_code, "NULL")
    did = disaster_type_map.get(
        (r.disaster_group, r.disaster_subgroup, r.disaster_type, r.disaster_subtype),
        "NULL",
    )
    start = int(r.start_year) if pd.notna(r.start_year) else "NULL"
    end = int(r.end_year) if pd.notna(r.end_year) else "NULL"
    deaths = r.total_deaths if pd.notna(r.total_deaths) else "NULL"
    affected = r.total_affected if pd.notna(r.total_affected) else "NULL"
    damage = r.total_damage_thousand_usd if pd.notna(r.total_damage_thousand_usd) else "NULL"

    disaster_values.append(
        f"('{r.disno}', {cid}, {did}, {start}, {end}, {deaths}, {affected}, {damage})"
    )

disaster_sql = (
    "INSERT INTO disasters (disno, country_id, disaster_type_id, start_year, end_year, total_deaths, total_affected, total_damage_thousand_usd) VALUES\n"
    + ",\n".join(disaster_values)
    + ";\n\n"
)

# ================================
# 5️. country_annual_temperatures (국가별 연평균 기온)
# ================================
temp_values = []
for _, r in df_temp.iterrows():
    cid = country_id_map.get(r.iso_code, "NULL")
    year = int(r.measurement_year)
    temp = r.avg_temperature_celsius
    temp_values.append(f"({cid}, {year}, {temp})")

temp_sql = (
    "INSERT INTO country_annual_temperatures (country_id, measurement_year, avg_temperature_celsius) VALUES\n"
    + ",\n".join(temp_values)
    + ";\n\n"
)

# ================================
# 6️. 전체 SQL 파일 통합 (하나로)
# ================================
final_sql = (
    "-- =============================\n"
    "-- INSERT Script for All Tables\n"
    "-- =============================\n\n"
    + continent_sql
    + country_sql
    + disaster_type_sql
    + disaster_sql
    + temp_sql
)

output_path = "/content/drive/MyDrive/4-2 빅데이터응용/dbinsert_1_5.sql"
with open(output_path, "w", encoding="utf-8-sig") as f:
    f.write(final_sql)

print(" SQL 파일 생성 완료:", output_path)